services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: challenge-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/challenge
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test@123
    ports:
      - "8080:8080"
    restart: unless-stopped

  mysql:
    image: 'mysql:8'
    container_name: mysql
    restart: always
    environment:
      - 'MYSQL_DATABASE=challenge'
      - 'MYSQL_ROOT_PASSWORD=Test@123'
    ports:
      - '3308:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: